variables:
  ASPNETCORE_ENVIRONMENT: "Development"
  ASPNETCORE_ACM_ALIYUN_GROUP: "Spidernet"
  ASPNETCORE_ACM_ALIYUN_DATA_ID: "Spidernet.Client"
stages:
  - build
  - push
  - deploy

develop_webapi_build:
  stage: build
  tags:
    - Linux
  script:
    - docker build -t spidernet-webapi:latest -f dockerfiles/WebAPIDockerfile .
    
develop_webapi_push:
  stage: push
  tags:
    - Linux
  script:
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
    - docker tag spidernet-webapi:latest guoyongchang/spidernet-webapi:develop-latest
    - docker push guoyongchang/spidernet-webapi:develop-latest

develop_webapi_deploy:
  stage: deploy
  tags:
    - Linux
  script:
    - docker rm -f $(docker ps -a | grep spidernet-webapi:develop-latest | awk '{print $1'})
    - docker run -p 6543:5001 -d guoyongchang/spidernet-webapi:develop-latest --name spidernet-webapi-develop